In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
data = pd.read_csv("../data/3.세종시_아파트(매매)_실거래가.csv", encoding = "utf-8")

In [3]:
data

,계약년월,계약일,시군구,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,해제사유발생일
0,201701,1,세종특별자치시 보람동,743,0,스타힐타워Ⅰ,16.9849,"8,600",7,2016,NaN
1,201701,1,세종특별자치시 종촌동,683,0,가재마을2단지,59.8652,"27,300",7,2014,NaN
2,201701,2,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),84.9894,"32,000",3,2015,NaN
3,201701,2,세종특별자치시 고운동,1706,0,가락마을8단지(고운뜰아파트),84.9800,"30,500",20,2015,NaN
4,201701,2,세종특별자치시 아름동,1284,0,범지기마을7단지 호반에코시티,84.9280,"31,300",6,2014,NaN
...,...,...,...,...,...,...,...,...,...,...,...
23592,202012,31,세종특별자치시 조치원읍 신흥리,398,0,신흥대우푸르지오,126.6976,"50,000",10,2006,NaN
23593,202012,31,세종특별자치시 조치원읍 죽림리,396,0,조치원죽림자이,128.9491,"44,000",2,2008,NaN
23594,202012,31,세종특별자치시 종촌동,656,0,가재마을10단지,84.9365,"73,500",4,2014,NaN
23595,202012,31,세종특별자치시 종촌동,644,0,가재마을6단지,84.6799,"60,000",6,2016,NaN
23596,202012,31,세종특별자치시 한솔동,947,0,첫마을3단지(퍼스트프라임),59.8300,"52,800",3,2011,NaN

In [5]:
df = gpd.read_file('../data/19.세종시_연령별_거주인구정보_격자.geojson', encoding='utf-8')
df.head()

,gid,201710_20대_거주인구수,201810_20대_거주인구수,201910_20대_거주인구수,202010_20대_거주인구수,201710_30대_거주인구수,201810_30대_거주인구수,201910_30대_거주인구수,202010_30대_거주인구수,201710_40대_거주인구수,...,202010_80대_거주인구수,201710_90대_거주인구수,201810_90대_거주인구수,201910_90대_거주인구수,202010_90대_거주인구수,201710_100세이상_거주인구수,201810_100세이상_거주인구수,201910_100세이상_거주인구수,202010_100세이상_거주인구수,geometry
0,다바667567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((127.12716 36.70773, 127.12716 ..."
1,다바667568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((127.12716 36.70863, 127.12716 ..."
2,다바668566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((127.12829 36.70683, 127.12828 ..."
3,다바668567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((127.12828 36.70773, 127.12828 ..."
4,다바668568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((127.12828 36.70863, 127.12828 ..."

In [6]:
pipwin install geojsonio

SyntaxError: invalid syntax (<ipython-input-6-d4e0a8efe6ed>, line 1)