In [2]:
pip install folium

Collecting folium
  Downloading folium-0.12.1-py2.py3-none-any.whl (94 kB)
Requirement already satisfied: requests in d:\python3_9_2\lib\site-packages (from folium) (2.25.1)
Collecting branca>=0.3.0Note: you may need to restart the kernel to use updated packages.
  Downloading branca-0.4.2-py3-none-any.whl (24 kB)
Requirement already satisfied: jinja2>=2.9 in d:\python3_9_2\lib\site-packages (from folium) (2.11.3)
Requirement already satisfied: numpy in d:\python3_9_2\lib\site-packages (from folium) (1.20.1+mkl)
Requirement already satisfied: idna<3,>=2.5 in d:\python3_9_2\lib\site-packages (from requests->folium) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in d:\python3_9_2\lib\site-packages (from requests->folium) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in d:\python3_9_2\lib\site-packages (from requests->folium) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\python3_9_2\lib\site-packages (from requests->folium) (1.26.4)

WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'd:\python3_9_2\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: MarkupSafe>=0.23 in d:\python3_9_2\lib\site-packages (from jinja2>=2.9->folium) (1.1.1)
Installing collected packages: branca, folium
Successfully installed branca-0.4.2 folium-0.12.1

In [3]:
import folium

In [6]:
from folium import plugins

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
fontpath = 'C:\Windows\Fonts/NanumBarunGothic.ttf'
font = fm.FontProperties(fname=fontpath, size=9)
plt.rc('font', family='NanumBarunGothic')
mpl.font_manager._rebuild()

In [8]:
import pandas as pd

In [12]:
df = pd.read_csv('../data/행정구역_시군구_별__성별_인구수_20210322190910.csv', encoding='cp949')
# df['sigun_code'] = df['sigun_code'].astype(str)
# df.head()

In [13]:
df

,행정구역(시군구)별,2020. 12,2020. 12.1,2020. 12.2,2021. 01,2021. 01.1,2021. 01.2,2021. 02,2021. 02.1,2021. 02.2
0,행정구역(시군구)별,총인구수 (명),남자인구수 (명),여자인구수 (명),총인구수 (명),남자인구수 (명),여자인구수 (명),총인구수 (명),남자인구수 (명),여자인구수 (명)
1,전국,51829023,25841029,25987994,51825932,25838512,25987420,51824142,25836561,25987581
2,서울특별시,9668465,4701723,4966742,9657969,4695999,4961970,9648606,4690282,4958324
3,부산광역시,3391946,1661000,1730946,3389388,1659527,1729861,3387761,1658540,1729221
4,대구광역시,2418346,1193109,1225237,2415813,1191656,1224157,2413191,1190244,1222947
5,인천광역시,2942828,1473943,1468885,2942452,1473639,1468813,2941705,1473245,1468460
6,광주광역시,1450062,717348,732714,1449115,716929,732186,1447953,716331,731622
7,대전광역시,1463882,730699,733183,1463291,730396,732895,1462064,729663,732401
8,울산광역시,1136017,583708,552309,1135370,583402,551968,1132953,582190,550763
9,세종특별자치시,355831,177568,178263,357871,178656,179215,359569,179528,180041
10,경기도,13427014,6754469,6672545,13449499,6765862,6683637,13471758,6777066,6694692
11,강원도,1542840,776505,766335,1541696,775727,765969,1540875,775186,765689
12,충청북도,1600837,811591,789246,1599658,811057,788601,1599122,810751,788371
13,충청남도,2121029,1082634,1038395,2119837,1082095,1037742,2119542,1082026,1037516
14,전라북도,1804104,896874,907230,1802748,896115,906633,1801319,895485,905834
15,전라남도,1851549,930615,920934,1850575,930132,920443,1849795,929889,919906
16,경상북도,2639422,1329211,1310211,2637639,1328384,1309255,2636747,1328167,1308580
17,경상남도,3340216,1681423,1658793,3338396,1680383,1658013,3336045,1679295,1656750
18,제주특별자치도,674635,338609,336026,674615,338553,336062,675137,338673,336464